// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRGsNpCboaOF2aJ-7rizSHgFUi0yFI5jI',
    appId: '1:1020071568080:web:fabce7a437023e4870f4d5',
    messagingSenderId: '1020071568080',
    projectId: 'personalmedicinereminder',
    authDomain: 'personalmedicinereminder.firebaseapp.com',
    storageBucket: 'personalmedicinereminder.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOl6LOfgeLHnLrPTMzIJGC_XZSeLjgeZM',
    appId: '1:1020071568080:android:882ba9374ebec5f370f4d5',
    messagingSenderId: '1020071568080',
    projectId: 'personalmedicinereminder',
    storageBucket: 'personalmedicinereminder.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3dkXnP2CBteDiWjK0tNX6dQ_xRbQR8Ps',
    appId: '1:1020071568080:ios:1d69f56f598b6ef070f4d5',
    messagingSenderId: '1020071568080',
    projectId: 'personalmedicinereminder',
    storageBucket: 'personalmedicinereminder.firebasestorage.app',
    iosBundleId: 'com.example.personalMedicineReminder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3dkXnP2CBteDiWjK0tNX6dQ_xRbQR8Ps',
    appId: '1:1020071568080:ios:1d69f56f598b6ef070f4d5',
    messagingSenderId: '1020071568080',
    projectId: 'personalmedicinereminder',
    storageBucket: 'personalmedicinereminder.firebasestorage.app',
    iosBundleId: 'com.example.personalMedicineReminder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRGsNpCboaOF2aJ-7rizSHgFUi0yFI5jI',
    appId: '1:1020071568080:web:e4ace2023d00ea5c70f4d5',
    messagingSenderId: '1020071568080',
    projectId: 'personalmedicinereminder',
    authDomain: 'personalmedicinereminder.firebaseapp.com',
    storageBucket: 'personalmedicinereminder.firebasestorage.app',
  );
}
